# modules :) in python modules are files that contains reusable codes like:
# functions variables classes 
# os module is built in module to intereact with the operating system

In [2]:
import os # import the os module so i can use the operating system features

In [ ]:
os.getcwd()#path where the jupyter notebook is located
os.listdir() #get the list of the files in the directory
# os.makedirs("New_demo_folder") #create new folder
os.listdir()#list all contents in the directory

['00_pFDS.ipynb', '01_pandas_numpy.ipynb', 'New_demo_folder']

# introduction to pandas and numpy

#arrays 
#1d arrays is series
#2d arrays is data frame
#by default indexing starts with 0 in pandas
#column name referred to as features
#one record is called observation

# excel         pandas
#worksheet     dataframe //
#column         series //
#row heading    index //
#row            row //
#empty cell     NaN(not a number) //

In [19]:
!pip install numpy

Requirement already satisfied: numpy in C:\Users\nigam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.4.4)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\nigam\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [22]:
import numpy as np
import pandas as pd

In [33]:
#creating an data frame
#data frame is a 2D table like data structure made of rows and columns similar to excel sheet/sql table
data = np.array([[2,3],[3,1],[6,0]])
df = pd.DataFrame(data,index = ['row_1','row_2','row_3'],
                  columns=['col_1','col_2'])
df#index for rows columns for columns pass list for conversion

       col_1  col_2
row_1      2      3
row_2      3      1
row_3      6      0

In [36]:
#data frame using lists 
data = [[2,3],[43,2],[4,9]]
df = pd.DataFrame(data,index =[1,2,3],columns=[1,2])
df

    1  2
1   2  3
2  43  2
3   4  9

In [48]:
#data frame using dictionary
states = ['Assam','Bihar','New_york']
population = [78000,123000,340000]
dict_states = {'States':states,'Population':population}
df_population = pd.DataFrame(dict_states,index=['state_1','state_2','state_3'])
df_population

           States  Population
state_1     Assam       78000
state_2     Bihar      123000
state_3  New_york      340000

In [60]:
# data frame using .csv file
#.csv files are referred to as dataset and when we read it using pandas it is referred to as df
df = pd.read_csv(r"C:\\Users\\nigam\\Downloads\\customers-100.csv")
df.head()#get first five index of the df
df.tail()#get last five index of the df
df.head(10)#get upto specific index of the df same for tail

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

os.getcwd()
'c:\\Users\\nigam\\Documents\\visual_studio_code\\python_for_ds'

In [75]:
df = pd.read_csv(r"C:\\Users\\nigam\\Downloads\\customers-100.csv")
print(df.shape)
pd.set_option('display.max_rows',1)#get each index upto the mark displayed and not the summary of the data frame
df

(100, 12)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

# Pandas attributes methods and functions
#attributes :) value associated with an object df.columns
#methods :) fcuntion which is defined in a class body df.head() df.tail()
#function :)  group of statements that perform a specific task min max len etc

#import kagglehub

##Download latest version
#path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

#print("Path to dataset files:", path)
#above code is for importing data of students performance

In [96]:
df = pd.read_csv('StudentsPerformance.csv')
print(df.shape)#get the shape of the df
print(df.dtypes)#get the dtype of each columns
print(df.index)#get the indexing format for the df
print(df.columns)#get the column names
print(df.gender)#get the values of a particular column

(1000, 8)
gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object
RangeIndex(start=0, stop=1000, step=1)
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')
0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

# important
#.name() calling a method/function Do/execute something
#.name accessing an attribute/property Get/store information

In [ ]:
df = pd.read_csv('StudentsPerformance.csv')
# df.info()#showing the info of the df
df.describe()#describing basic statistics of the df
print(len(df))#get length of the df/no of rows in df
print(max(df.index))#obtaiing the highest index of the df
print(min(df.index))#obtaining the minimum index of the df
print(df.dtypes)#obtaiing the data type of the columns
print(type(df))#obtaining the data type
round(df,2)#rounding the values of the dataset
round(df.describe(),2)#rounding of the basic statistics of the df upto 2 decimals

1000
999
0
gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object
<class 'pandas.DataFrame'>

       math score  reading score  writing score
count     1000.00        1000.00        1000.00
mean        66.09          69.17          68.05
std         15.16          14.60          15.20
min          0.00          17.00          10.00
25%         57.00          59.00          57.75
50%         66.00          70.00          69.00
75%         77.00          79.00          79.00
max        100.00         100.00         100.00

In [ ]:
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df['gender']#selecting a column in the df
type(df['gender'])#one d arrays are series in pandas

pandas.Series

In [119]:
df['gender'].index
df['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: str

In [136]:
#selecting two or more columns in df
#single pair square bracket series
#two pair df
#can't select two or more columns with the "df." something
df = pd.read_csv('StudentsPerformance.csv')
df[['gender','math score']]#selecting multiple columns
type(df[['gender','math score']])
df[['gender','math score','writing score','reading score']].describe().round(2)

       math score  writing score  reading score
count     1000.00        1000.00        1000.00
mean        66.09          68.05          69.17
std         15.16          15.20          14.60
min          0.00          10.00          17.00
25%         57.00          57.75          59.00
50%         66.00          69.00          70.00
75%         77.00          79.00          79.00
max        100.00         100.00         100.00

In [143]:
#adding new column to the df
df = pd.read_csv('StudentsPerformance.csv')
df['language score'] = 70#all values is same in the column
print(df.ndim)

2

In [139]:
import numpy as np
import random

In [154]:
language_score = np.arange(0,1000)
df['language score']=language_score
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [184]:
#create random integers array between 1 and 1000
int_language_score = np.random.randint(1,101,size=1000)
df['language score'] = int_language_score
# del df['language_score'
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,71
1,female,group C,some college,standard,completed,69,90,88,20
2,female,group B,master's degree,standard,none,90,95,93,16
3,male,group A,associate's degree,free/reduced,none,47,57,44,27
4,male,group C,some college,standard,none,76,78,75,34

In [186]:
#create a random float numbers array between  and 100
np.random.uniform(1,100,size=100).round(2)

array([37.17, 13.09, 76.61, 36.01, 45.32, 17.14,  7.94, 45.19, 31.8 ,
       30.34, 66.1 , 57.23, 65.64, 29.13, 37.7 , 42.68, 14.72, 94.36,
       39.18, 58.02, 42.32, 90.72, 53.07, 55.75, 65.98, 29.25, 68.56,
       83.89, 97.96, 43.24, 81.26, 12.55,  4.17, 44.17, 78.25, 88.3 ,
        8.58, 42.47, 88.19, 75.12,  5.82, 69.32,  6.65, 66.21, 81.52,
       19.84, 12.17, 70.18, 75.21, 43.33, 70.21, 34.42, 34.73, 51.19,
       93.98, 80.5 , 71.13, 96.71, 15.24, 62.38, 55.25, 78.56,  8.58,
        9.51, 29.81, 14.27, 36.14, 86.14, 64.7 , 80.43, 56.78, 25.58,
       29.19,  5.08, 66.  , 81.56, 65.78, 41.89, 53.59, 64.24, 67.71,
       53.3 , 99.77, 86.01, 58.34, 45.16, 24.17, 48.21, 13.99, 35.99,
       74.97, 86.9 , 83.25, 56.3 , 53.14, 35.79, 74.77,  3.02, 91.81,
       24.78])