# modules :) in python modules are files that contains reusable codes like:
# functions variables classes 
# os module is built in module to intereact with the operating system

In [1]:
import os # import the os module so i can use the operating system features

In [2]:
os.getcwd()#path where the jupyter notebook is located
os.listdir() #get the list of the files in the directory
# os.makedirs("New_demo_folder") #create new folder
os.listdir()#list all contents in the directory

['.git',
 '00_pFDS.ipynb',
 '01_pandas_numpy.ipynb',
 'New_demo_folder',
 'README.md',
 'StudentsPerformance.csv']

# introduction to pandas and numpy

#arrays 
#1d arrays is series
#2d arrays is data frame
#by default indexing starts with 0 in pandas
#column name referred to as features
#one record is called observation

# excel         pandas
#worksheet     dataframe //
#column         series //
#row heading    index //
#row            row //
#empty cell     NaN(not a number) //

In [3]:
!pip install numpy

Requirement already satisfied: numpy in C:\Users\nigam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.4.4)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\nigam\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd

In [5]:
#creating an data frame
#data frame is a 2D table like data structure made of rows and columns similar to excel sheet/sql table
data = np.array([[2,3],[3,1],[6,0]])
df = pd.DataFrame(data,index = ['row_1','row_2','row_3'],
                  columns=['col_1','col_2'])
df#index for rows columns for columns pass list for conversion

       col_1  col_2
row_1      2      3
row_2      3      1
row_3      6      0

In [6]:
#data frame using lists 
data = [[2,3],[43,2],[4,9]]
df = pd.DataFrame(data,index =[1,2,3],columns=[1,2])
df

    1  2
1   2  3
2  43  2
3   4  9

In [7]:
#data frame using dictionary
states = ['Assam','Bihar','New_york']
population = [78000,123000,340000]
dict_states = {'States':states,'Population':population}
df_population = pd.DataFrame(dict_states,index=['state_1','state_2','state_3'])
df_population

           States  Population
state_1     Assam       78000
state_2     Bihar      123000
state_3  New_york      340000

In [8]:
# data frame using .csv file
#.csv files are referred to as dataset and when we read it using pandas it is referred to as df
df = pd.read_csv(r"C:\\Users\\nigam\\Downloads\\customers-100.csv")
df.head()#get first five index of the df
df.tail()#get last five index of the df
df.head(10)#get upto specific index of the df same for tail

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

os.getcwd()
'c:\\Users\\nigam\\Documents\\visual_studio_code\\python_for_ds'

In [9]:
df = pd.read_csv(r"C:\\Users\\nigam\\Downloads\\customers-100.csv")
print(df.shape)
pd.set_option('display.max_rows',1)#get each index upto the mark displayed and not the summary of the data frame
df

(100, 12)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

# Pandas attributes methods and functions
#attributes :) value associated with an object df.columns
#methods :) fcuntion which is defined in a class body df.head() df.tail()
#function :)  group of statements that perform a specific task min max len etc

#import kagglehub

##Download latest version
#path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

#print("Path to dataset files:", path)
#above code is for importing data of students performance

In [10]:
df = pd.read_csv('StudentsPerformance.csv')
print(df.shape)#get the shape of the df
print(df.dtypes)#get the dtype of each columns
print(df.index)#get the indexing format for the df
print(df.columns)#get the column names
print(df.gender)#get the values of a particular column

(1000, 8)
gender    str
         ...
Length: 8, dtype: object
RangeIndex(start=0, stop=1000, step=1)
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')
0    female
      ...
Name: gender, Length: 1000, dtype: str

# important
#.name() calling a method/function Do/execute something
#.name accessing an attribute/property Get/store information

In [11]:
df = pd.read_csv('StudentsPerformance.csv')
# df.info()#showing the info of the df
df.describe()#describing basic statistics of the df
print(len(df))#get length of the df/no of rows in df
print(max(df.index))#obtaiing the highest index of the df
print(min(df.index))#obtaining the minimum index of the df
print(df.dtypes)#obtaiing the data type of the columns
print(type(df))#obtaining the data type
round(df,2)#rounding the values of the dataset
round(df.describe(),2)#rounding of the basic statistics of the df upto 2 decimals

1000
999
0
gender    str
         ...
Length: 8, dtype: object
<class 'pandas.DataFrame'>

       math score  reading score  writing score
count      1000.0         1000.0         1000.0
...           ...            ...            ...

[8 rows x 3 columns]

In [12]:
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df['gender']#selecting a column in the df
type(df['gender'])#one d arrays are series in pandas

pandas.Series

In [13]:
df['gender'].index
df['gender'].head()

0    female
      ...
Name: gender, Length: 5, dtype: str

In [14]:
#selecting two or more columns in df
#single pair square bracket series
#two pair df
#can't select two or more columns with the "df." something
df = pd.read_csv('StudentsPerformance.csv')
df[['gender','math score']]#selecting multiple columns
type(df[['gender','math score']])
df[['gender','math score','writing score','reading score']].describe().round(2)

       math score  writing score  reading score
count      1000.0         1000.0         1000.0
...           ...            ...            ...

[8 rows x 3 columns]

In [15]:
#adding new column to the df
df = pd.read_csv('StudentsPerformance.csv')
df['language score'] = 70#all values is same in the column
print(df.ndim)

2

In [16]:
import numpy as np
import random

In [17]:
language_score = np.arange(0,1000)
df['language score']=language_score
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0

In [18]:
#create random integers array between 1 and 1000
int_language_score = np.random.randint(1,101,size=1000)
df['language score'] = int_language_score
# del df['language_score'
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,85

In [19]:
#create a random float numbers array between  and 100
np.random.uniform(1,100,size=100).round(2)

array([63.2 , 83.5 , 86.15, 23.44, 45.48, 33.84, 57.38, 60.2 ,  9.73,
       30.47, 76.86, 74.61, 62.38, 92.46, 39.84, 90.57, 40.17, 86.58,
       22.99, 34.39, 42.64, 54.38, 79.55, 62.4 , 29.76, 94.57, 14.38,
       39.69, 28.92, 84.28, 17.  , 78.58, 85.9 , 69.  , 66.04, 34.28,
       91.65, 21.15, 69.55,  6.39, 12.98, 51.13, 79.26, 28.48, 33.86,
       26.83, 17.66, 31.19, 30.45, 72.83, 87.4 , 88.31,  6.89, 58.35,
       63.46, 88.13, 19.53, 57.71, 24.08, 27.78, 53.97, 57.28, 89.38,
       99.56, 24.79, 94.88, 93.6 , 51.85, 34.05, 10.8 , 33.08, 59.08,
       20.31, 32.04, 51.5 , 15.37, 79.89, 11.78, 53.74, 31.7 , 40.55,
       26.71, 29.62, 19.08, 82.09, 63.65, 30.27, 67.13, 72.67, 64.12,
       53.35,  5.62, 90.84, 33.98, 44.87, 89.6 , 29.76, 62.32, 19.01,
       95.92])

import numpy as np
ex = np.random.randint(0,500)#create a random number generator
ex

In [20]:
#create a random df consisting of float numbers in a range
ex = np.random.uniform(1,100,1000).round(2)
print(ex)

[ 5.06 59.93 54.76 41.64 56.03 31.51 97.2  46.88 17.17 68.03 12.1  45.84
 39.76 67.15 25.47 58.41 16.77 23.72 78.88  3.38 58.82 61.3  23.35 82.8
 93.68 15.12 14.68 72.18 46.98 97.72 64.04 17.87 13.74 45.96 55.57 70.7
 43.38 47.75 18.88 86.55 35.27 84.03  8.85 60.97 19.82 74.23 59.53 36.85
 16.05 76.62 87.91 69.6  77.82 49.77 12.03 77.14 61.44 68.58 64.49 20.29
 77.38 88.25 90.99 46.26 76.86 37.98 47.65 37.59 29.19 11.31 40.13 45.05
 65.23 77.52 20.03 51.08 90.24 63.99 98.54  6.26 38.89 62.12 93.05 48.78
 89.18 19.21 71.01  6.36 81.63 86.75 98.   99.14 94.05 86.26 14.7  73.51
 78.82 16.1   9.09 74.57 39.49 66.17 87.57 12.54 83.93 20.75 10.11 81.08
 55.1  86.48 89.74 78.5  25.08 56.58 68.41  4.51 90.01 89.76 91.74 74.88
 59.77 65.32 50.17 71.36 59.83 27.06  4.93 56.6  45.97 50.64 28.29 53.85
  5.7  86.99 63.31 37.19 27.5  86.45 66.47 63.6  64.67 31.87 94.1  27.46
 21.95 99.96 54.33 22.19  6.45  2.55 70.59  2.49 70.09 35.66 78.36 27.01
  8.03 40.06 47.88 95.42 72.83 41.54 77.12 96.92 45.63 22.91 30.42 36.05
  3.92 45.38 22.04 94.89 22.31 59.55 83.8  76.02 26.89 31.29 31.88 97.58
 80.2  16.79 10.05 79.95 81.43 42.58 17.03 78.64 85.25 96.3   7.73 37.77
 69.52 99.44  7.7  50.02 17.36 20.97 53.16 75.49 23.18  6.91 18.   96.93
 76.19 77.69 73.63 46.06 25.12  6.1  20.08 88.47 88.53 97.17 49.04 18.31
 46.35 49.18 27.1  51.32 99.16  1.04 50.37 75.03 46.36 48.   54.19  7.
 49.35 90.68 83.14 18.68 80.83 16.98 38.78 83.14 69.79 55.09 41.99 64.23
 41.92 89.11 30.88 19.44 15.86 19.5  98.41 36.26 14.86 93.43 71.98 23.3
 73.6  35.49 44.62 65.14 25.46 71.56 79.53 84.06 44.89 49.33  6.7  84.24
  4.28 24.11 69.95 62.42 90.36 76.55  5.16 73.54 53.23 67.76 23.56 80.09
 45.97 37.87 95.38 51.29 28.9  71.09 42.03 68.34 24.95 96.51 94.65 91.79
 40.45 57.17 21.13 14.86  9.86 90.41 76.5  91.29 94.83 65.8  32.62 24.49
 78.43 86.58 21.37 72.45 37.58 48.51  3.16 20.97 99.39 18.11 10.17  5.9
 12.35 83.88  8.82 34.49  4.07 69.93 15.17 89.5  97.58 86.19 36.08  6.91
 54.61  6.58 59.49 70.43 43.14 97.91  8.76 93.15 21.28 76.07 28.5   1.08
 14.02 76.68 81.57  9.76 69.04 34.1  26.82 86.11 87.81 82.33 57.37 91.14
 14.03  3.39 43.24 42.62 78.7  54.09 82.67 91.82  4.69 13.16 97.86 82.1
 96.63 86.61 39.02 42.93 60.61 36.46 92.89 25.06 68.69 18.16 45.01 14.54
  1.53 78.71 68.72 28.6  97.61  3.25 53.29 88.68 88.12 28.46 74.15 53.17
 66.26 73.31 74.72 28.72 94.05 53.87 91.15 18.88 33.43 56.26 69.52 32.69
 65.58 37.38 34.19 95.29 30.2  48.16 80.2  22.25 31.26 71.49 21.21 78.91
  5.6  53.84 93.89 99.18 89.02 95.06 68.83 66.16 63.98 40.9  76.89 80.41
 26.77 66.98 14.92 57.02 87.8  85.92 13.64 45.18 29.67 22.96 59.19 67.32
 70.    9.63 22.09 31.7  41.96 77.77 81.25 93.79 78.79 71.52 95.87 63.07
 77.81 99.81 97.02  9.97 27.09 50.02 81.06 38.86 65.07 62.28 37.55 83.9
 59.69 57.23 60.4  53.73 12.49  6.42 34.81 51.11 19.98 11.01 24.1  22.29
 84.3   4.44 37.83 12.66  8.83 97.46 41.27 26.85 11.37 31.08 24.96 33.62
 38.13 22.53 73.78 15.81 42.48 16.69  9.37  4.84 54.77 39.31 62.53 39.15
 18.27 46.35 15.07 40.29 14.67 15.85 31.88  6.4  92.22 33.14 49.11 76.51
 71.81 71.07  7.71 50.52 58.7  33.95 58.82 69.89 64.36 50.02 72.46  3.69
 20.35 50.55 51.04 36.55 82.25 70.77  1.1  48.63  3.06 59.2  27.29 12.94
 74.68 56.85 25.51 36.18 48.98 19.03 98.03 56.78 20.03 55.82 65.78  2.2
 99.52 67.65 87.9  14.26 40.49 62.68 27.67 11.61 39.77 74.87 16.01  6.81
 92.04 93.49 70.44 76.65 59.99 58.98 54.42 85.5  60.25 12.05 59.97 91.68
  1.57 94.28 88.12  4.17 87.11 37.4  77.39 18.04 86.48 74.28 88.59 51.52
 32.27 92.12 83.02 77.58 90.12 24.32  9.41 72.21  6.26 80.73 85.98 10.22
 66.35  2.8  67.63 95.   38.37 96.24  2.02 13.35 34.43 89.63 28.4  88.29
 59.87 28.31 76.61 50.42 42.81  7.9  98.97 68.23 97.37 28.01 79.81 44.54
  3.6  25.78 75.93 54.89 11.92 93.5  41.21 27.62 97.31  9.59 40.31 64.61
 75.54 11.51 99.75 47.46 29.89 27.84 80.79 17.1  47.61 30.48 13.   80.59
 63.04 50.6  37.71 57.95 49.28 10.3  54.15 11.88 11.78 29.69 19.61 89.89
 98.75 13.75 29.55 68.14 64.11 96.74 92.58 13.06 83.96  6.66 90.83 63.06
 81.46  1.94 73.16 95.94 31.01  8.43 22.14 41.92 86.01  9.82  4.54 17.87
 40.4  31.79  6.94 36.83 26.93 92.09 85.97 28.46 11.41  6.74 88.95 65.44
 81.47 67.82 39.72  7.29 20.66 80.42 42.3  65.62 41.53 27.47 65.78 47.41
 86.19 65.76 91.03 15.05 61.03 11.37 14.37 20.36  2.84 63.64 51.    3.46
 33.9  88.49 68.05 85.71 68.29 36.92 87.19 30.72 66.07 25.58 21.29 73.43
 77.52 48.67  1.07 53.28 73.48 90.1  15.82 30.63 29.16 44.28 61.96 95.15
 61.64 94.46 65.63 93.8  64.37 10.77 38.01 81.75 18.44 10.51 52.44  1.74
 80.93 66.84 17.14 62.2   2.61 97.18 99.25  1.15 97.19 31.52 22.31 23.05
 48.32 52.89 79.25 59.12 17.7  17.7  13.53 12.5   3.38 88.53 73.   49.66
 88.91 17.63 27.96 76.83 28.67 84.75 66.91 52.56 94.97 12.25 21.68 89.69
 44.17 12.81 38.27 34.07 65.37 55.94 75.08 49.89 67.76 24.17 44.57 14.08
 88.71 55.24 63.88 24.68 44.48 79.58 21.63 10.44 55.66 22.87 30.07 80.38
 15.72 31.56 77.2  59.78  4.3  24.61 60.67 61.74 95.89 49.03 59.88 80.87
 68.35  2.2  82.89 13.76 94.81  1.83 96.82  9.47 67.85 97.13 77.72  6.2
 23.36 15.01 57.32 83.47 97.63 78.29 69.82 31.25 49.52 38.68 71.34 45.38
 96.48 66.34 40.99 19.9  80.   94.13 35.27 83.82 77.97 80.46 77.36 31.28
 66.78 36.05 88.17 97.95 37.95 64.36 39.85 92.55 91.54 21.31 23.87 99.82
 52.22 96.27 59.42 88.62 50.34 94.52 34.58 38.51 17.01  1.24 79.89 70.29
 85.04 59.18 36.82 56.79 96.19 34.37 70.62 13.34 90.81 11.71 11.6  26.87
 91.38 24.26 93.85 72.51 59.29 20.05  3.22  2.62 58.29 70.63 95.94 15.22
 34.89 50.46 31.33 44.36 42.6  35.03 19.64 36.33 53.29 73.04 65.9  79.54
 86.87 53.03 85.46  9.3  92.05  3.35 20.11 62.23 53.31 45.63 38.85 89.84
 33.61 15.42 27.78 50.06 31.17 76.5  21.64 80.75 25.4  20.89 82.92 40.91
 87.67 12.83 97.99 74.07 70.92 51.65 98.56 40.3  71.23 62.54 97.97 10.74
 32.27 41.65 36.53 86.74 26.57  4.18  3.47  7.11 87.89 85.42 57.06  1.79
 79.16 74.57 96.38 54.89 51.26 83.01 32.06 26.6  54.36 37.48 66.18 54.75
 98.31 49.07 70.08 14.75 27.69 99.05 87.71 31.62 65.23  6.55 57.25 28.64
 49.85 32.94 35.42 17.16 93.97 37.75 54.63 22.25  6.2  77.38 43.27 52.28
 11.79 84.45 19.88 86.15]

In [21]:
#adding a new column with assign
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
score_1 = np.random.randint(1,100,size = 1000)
score_2 = np.random.randint(1,100,size = 1000)
series_1 = pd.Series(score_1,index = np.arange(0,1000))
series_2 = pd.Series(score_2,index = np.arange(0,1000))
df = df.assign(score1 = series_1,score2 = series_2)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,89,38

In [22]:
#adding a new column with insert 
demo_random_data = np.random.randint(0,45,size=1000)
demo_series = pd.Series(demo_random_data,index = np.arange(0,1000))
# df.insert(3,'demo column',demo_random_data) here column added using insert check for hashable once again
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,89,38

# operations on df

In [23]:
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df.describe()

       math score  reading score  writing score
count      1000.0         1000.0         1000.0
...           ...            ...            ...

[8 rows x 3 columns]

In [24]:
#calculating on single column
print(df['math score'].sum())#calculating total of a particular column
print(df['math score'].count())
print(df['math score'].mean())
print(df['math score'].median())
print(df['math score'].mode())
print(df['math score'].std())
print(df['math score'].min())
print(df['math score'].max())

66089
1000
66.089
66.0
0    65
Name: math score, dtype: int64
15.16308009600945
0
100

In [25]:
#calculation on multiple columns
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df['math score'] + df['reading score'] + df['writing score']#summing multiple column values
df['average score']=(df['math score'] + df['reading score'] + df['writing score'])/3
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.666667

In [26]:
df.head().round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67

In [27]:
#value counts
df['parental level of education'].value_counts(normalize=True)
len(df['average score'].value_counts(normalize=True).round(2))

194

In [28]:
#sorting a df
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
df.sort_values(by='math score')#by can be removed still same answer
df.sort_values('math score',ascending=False)
df.sort_values(['math score','reading score'],ascending=True).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10

In [29]:
#update values in df
df.sort_values(['math score','reading score'],ascending=False,inplace=True)

In [30]:
#sorting with text data
df.sort_values(['gender','parental level of education','race/ethnicity'],ascending=True,
               key= lambda col:col.str.lower()).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
614,female,group A,associate's degree,standard,none,82,93,93

In [31]:
#create index
import random
import numpy as np
import pandas as pd
df = pd.read_csv('StudentsPerformance.csv')
new_index = np.arange(0,1000)
random.shuffle(new_index)
df['new_index_col'] = new_index
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index_col
0,female,group B,bachelor's degree,standard,none,72,72,74,966

In [33]:
#set index method set new column as the index
df.set_index('new_index_col').sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index_col,,,,,,,,
0,female,group B,bachelor's degree,standard,none,97,97,96