# Project #1 web scraping with pandas

In [2]:
#reading a single csv file from website and renaming columns
import pandas as pd
df_data = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')
df_data.head()
df_data.rename(columns= {'FTHG':'home_goals','FTAG':'away_goals'},
               inplace=True)#updating the changes not copy
df_data.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [3]:
#reading multiple csv files from website
root = 'https://www.football-data.co.uk/mmz4281/2526/'#create root variable for all the links ie the part common in all the links
leagues = [ 'E0' , 'E1' , 'E2' , 'E3' , 'EC']#list where the difference lies in all the links
frames = []#empty list to store all the df
for league in leagues:#loop through the links to read it
    df = pd.read_csv( root +  league + ".csv",
                     encoding='unicode_escape')
    frames.append(df)
df.head()

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12

In [4]:
len(frames)#total how many links scanned
for i in range(5):
    print(frames[i].head())

  ï»¿Div        Date   Time     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0     E0  15/08/2025  20:00    Liverpool  Bournemouth     4     2   H     1
1     E0  16/08/2025  12:30  Aston Villa    Newcastle     0     0   D     0
2     E0  16/08/2025  15:00     Brighton       Fulham     1     1   D     0
3     E0  16/08/2025  15:00   Sunderland     West Ham     3     0   H     0
4     E0  16/08/2025  15:00    Tottenham      Burnley     3     0   H     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     2.03     1.78   2.07   1.85     2.03     1.88     1.94
1     0  ...     2.05     1.80   2.02   1.89     2.06     1.80     1.95
2     0  ...     1.83     2.03   1.93   2.00     1.84     2.03     1.80
3     0  ...     1.95     1.90   1.97   1.95     1.95     1.94     1.86
4     0  ...     1.98     1.88   1.99   1.93     1.98     1.91     1.88

   AvgCAHA  BFECAHH  BFECAHA
0     1.76     2.14     1.86
1     1.74     2.14     1.86
2     1.96     1.91     2.08
3     1.78     2.02     1.97
4     1.83     2.07     1.92

[5 rows x 132 columns]
  ï»¿Div        Date   Time       HomeTeam AwayTeam  FTHG  FTAG FTR  HTHG  \
0     E1  08/08/2025  20:00     Birmingham  Ipswich     1     1   D     0
1     E1  09/08/2025  12:30       Charlton  Watford     1     0   H     0
2     E1  09/08/2025  12:30       Coventry     Hull     0     0   D     0
3     E1  09/08/2025  12:30    Southampton  Wrexham     2     1   H     0
4     E1  09/08/2025  15:00  Middlesbrough  Swansea     1     0   H     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.88     1.98   1.81   2.12     1.88     1.98     1.81
1     0  ...     1.95     1.90   1.95   1.95     1.95     1.90     1.86
2     0  ...     1.88     1.98   1.95   1.95     1.91     1.98     1.87
3     1  ...     1.90     1.95   1.75   2.18     1.90     1.95     1.84
4     0  ...     2.05     1.75   2.00   1.91     2.05     1.82     2.00

   AvgCAHA  BFECAHH  BFECAHA
0     1.94     1.90     2.10
1     1.83     2.03     1.95
2     1.82     1.97     2.01
3     1.91     1.92     2.07
4     1.76     2.16     1.85

[5 rows x 132 columns]
  ï»¿Div        Date   Time   HomeTeam       AwayTeam  FTHG  FTAG FTR  HTHG  \
0     E2  01/08/2025  20:00      Luton  AFC Wimbledon     1     0   H     0
1     E2  02/08/2025  12:30    Cardiff      Peterboro     2     1   H     0
2     E2  02/08/2025  15:00  Blackpool      Stevenage     2     3   A     1
3     E2  02/08/2025  15:00   Bradford        Wycombe     2     1   H     2
4     E2  02/08/2025  15:00     Burton      Mansfield     2     1   H     1

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.93     1.93   1.93   1.95     1.98     1.93     1.91
1     1  ...     1.85     2.00   1.87   2.03     1.90     2.00     1.85
2     2  ...     1.93     1.93   1.94   1.94     1.94     1.93     1.84
3     0  ...     1.73     2.08   1.90   1.99     1.77     2.20     1.72
4     0  ...     2.00     1.85   1.69   2.26     2.00     1.85     1.93

   AvgCAHA  BFECAHH  BFECAHA
0     1.82     1.94     2.01
1     1.88     1.93     2.04
2     1.87     1.94     2.04
3     2.02     1.80     2.22
4     1.79     2.04     1.93

[5 rows x 132 columns]
  ï»¿Div        Date   Time      HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0     E3  02/08/2025  15:00    Accrington      Gillingham     1     1   D
1     E3  02/08/2025  15:00        Barnet  Fleetwood Town     0     2   A
2     E3  02/08/2025  15:00   Bristol Rvs       Harrogate     0     1   A
3     E3  02/08/2025  15:00     Cambridge      Cheltenham     1     0   H
4     E3  02/08/2025  15:00  Chesterfield          Barrow     1     0   H

   HTHG  HTAG  ... B365CAHA PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA  \
0     0     0  ...     1.88  1.76   2.12     1.98     1.88     1.92     1.83
1     0     1  ...     1.85  2.29   1.65     2.08     1.85     2.00     1.74
2     0     0  ...     2.03  1.85   2.00     1.85     2.03     1.78     1.96
3     0     0  ...     1.88  1.88   1.97     1.98     1.88     1.90     1.83
4     1     0  ...     2.03  1.79   2.06     1.80     2.07     1.73     2.02

   BFECAHH  BFECAHA  Unnamed: 132
0     2.09     1.88           NaN
1     2.04     1.93           NaN
2     1.88     2.12           NaN
3     1.98     2.00           NaN
4     1.87     2.13           NaN

[5 rows x 133 columns]
  ï»¿Div        Date   Time        HomeTeam   AwayTeam  FTHG  FTAG FTR  HTHG  \
0     EC  09/08/2025  15:00      Altrincham  Aldershot     3     2   H     2
1     EC  09/08/2025  15:00    Boreham Wood   Rochdale     0     2   A     0
2     EC  09/08/2025  15:00   Brackley Town  Eastleigh     1     0   H     1
3     EC  09/08/2025  15:00  Braintree Town    Halifax     3     0   H     2
4     EC  09/08/2025  15:00       Gateshead   Southend     0     3   A     0

   HTAG  ... B365CAHH B365CAHA  PCAHH  PCAHA  MaxCAHH  MaxCAHA  AvgCAHH  \
0     0  ...     1.90     1.90   1.92   1.93     1.90     1.90     1.86
1     0  ...     2.00     1.80   2.05   1.82     2.02     1.80     1.96
2     0  ...     2.00     1.80   2.14   1.72     2.03     1.80     1.96
3     0  ...     1.93     1.88   1.97   1.88     1.93     1.88     1.88
4     1  ...     1.83     1.98   1.67   2.19     1.83     2.04     1.75

   AvgCAHA  BFECAHH  BFECAHA
0     1.84     2.00     1.99
1     1.75     2.06     1.89
2     1.75     2.06     1.84
3     1.82     1.97     1.98
4     1.96     1.84     2.12

[5 rows x 124 columns]

In [5]:
#above scanning was done only for one season but what if we wanted data for multiple seasons
#scanning for mulitple seasons
leagues = [ 'E0' , 'E1' , 'E2' , 'E3' , 'EC']
frames = []
root = 'https://www.football-data.co.uk/mmz4281/'
for league in leagues:
    for season in range(20,26):
        df = pd.read_csv( root + str(season) + str(season+1) +  '/' + league +'.csv',
                         encoding='unicode_escape')
        df['season']=str(season) + str(season+1)
        df['league']=league
        frames.append(df)
data = pd.concat(frames,ignore_index=True)
data.head()

C:\Users\nigam\AppData\Local\Temp\ipykernel_19852\4094878762.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['season']=str(season) + str(season+1)
C:\Users\nigam\AppData\Local\Temp\ipykernel_19852\4094878762.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['league']=league

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA,Unnamed: 132
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
len(frames)#total df

30

In [7]:
data[['season','league']].head()
frames[29]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,season,league
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99,2526,EC
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89,2526,EC
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84,2526,EC
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98,2526,EC
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12,2526,EC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN,2526,EC
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN,2526,EC
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN,2526,EC
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN,2526,EC
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN,2526,EC

TypeError: 'Index' object is not callable

# organize all the data in dictionary

In [12]:
#create a dictionary with original name of league as key
dict_countries = {
    'spanish la liga':'sp1', 'spanish segunda division':'sp2',
    'german bundesliga':'d1',
    'english premier league':'e0','english league 1':'e2'
}
dict_countries['spanish la liga']

'sp1'

In [17]:
for league in dict_countries:
    print(dict_countries[league])

sp1
sp2
d1
e0
e2